import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactQueryClientProvider } from "./utils/ReactQueryClientProvider";
import { UserProvider } from "./utils/UserProvider";
import { VipProvider } from "./utils/VipProvider";
import { AddAuctionsProvider } from "./utils/AddAuctionsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Var",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AddAuctionsProvider>
        <VipProvider>
          <UserProvider>
            <body className={inter.className}>
              <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
            </body>
          </UserProvider>
        </VipProvider>
      </AddAuctionsProvider>
    </html>
  );
}
